[package]
	authors     = ["Ian Pratt <ianjdpratt@gmail.com>"]
	description = "Manage and backup dotfiles with ease!"
	edition     = "2021"
	name        = "dotback"
	version     = "0.0.0"

[dependencies]
	clap      = { version = "4.0.32", features = ["derive"] }
	dialoguer = "0.10.2"
	#  console   = "0.15.4"
	#  serde     = { version = "1.0.152", features = ["derive"] }
	#  toml      = "0.5.10"
