[workspace]
	default-members = [".", "dotbak-core"]
	members         = [".", "dotbak-core"]
	resolver        = "2"

	# Workspace definitions to be used by all members of the workspace.
	[workspace.package]
		authors = ["Ian Pratt <ianjdpratt@gmail.com>"]
		edition = "2021"
		license = "AGPL-3.0"
		version = "0.0.0"

[package]
	authors     = { workspace = true }
	description = "Manage and backup dotfiles with ease!"
	edition     = { workspace = true }
	license     = { workspace = true }
	name        = "dotbak"
	version     = { workspace = true }

[dependencies]
	# CLI parsing
	clap = { version = "4", features = ["derive"] }

	# Error handling
	miette = { version = "5", features = ["fancy"] } # For pretty errors

	# Dotbak core
	dotbak-core = { path = "dotbak-core" }
