[package]
	authors     = ["Ian Pratt <ianjdpratt@gmail.com>"]
	description = "Manage and backup dotfiles with ease!"
	edition     = "2021"
	name        = "dotback"
	version     = "0.0.0"

[dependencies]

	# CLI parsing
	clap = { version = "4", features = ["derive"] }

	# Configuration serialization/deserialization
	confy = "0.5"
	serde = { version = "1", features = ["derive"] }

	# Error handling
	miette    = "5"
	thiserror = "1"
