[package]
  authors     = ["Ian Pratt <ianjdpratt@gmail.com>"]
  description = "Manage and backup dotfiles with ease!"
  edition     = "2021"
  name        = "dotback"
  version     = "0.1.0"

[dependencies]
  clap = "4.0.32"
