[package]
	authors     = ["Ian Pratt <ianjdpratt@gmail.com>"]
	description = "Manage and backup dotfiles with ease!"
	edition     = "2021"
	name        = "dotbak"
	version     = "0.0.0"

[dependencies]

	# CLI parsing
	clap = { version = "4", features = ["derive"] }

	# Configuration serialization/deserialization
	serde = { version = "1", features = ["derive"] }
	toml  = "0.7"

	# Error handling
	miette    = "5"
	thiserror = "1"

	# Filesystem
	dirs = "5"   # Getting the user's home directory
	glob = "0.3" # For globbing files/directories
