[package]
	authors     = ["Ian Pratt <ianjdpratt@gmail.com>"]
	description = "Manage and backup dotfiles with ease!"
	edition     = "2021"
	name        = "dotback"
	version     = "0.0.0"

[dependencies]
	anyhow    = "1.0.68"
	clap      = { version = "4.0.32", features = ["derive"] }
	dialoguer = "0.10.2"
	home      = "0.5.4"
	serde     = { version = "1.0.152", features = ["derive"] }
	snafu     = "0.7.4"
	toml      = "0.5.10"
	# glob      = "0.3.1"
	# console   = "0.15.4"
